- hosts: CaptivePortal
  become: "{{ become | default('yes') }}"
  roles:
    - openwisp-wifi-login-pages
  vars:
    # Captive Portal
    wifi_login_pages_domains: ["wifi.nnxx.ninux.org"]
    wifi_login_pages_ssl_cert: "/etc/ssl/openwisp/fullchain.pem"
    wifi_login_pages_ssl_key: "/etc/ssl/openwisp/key.pem"

  # Let's
#  pre_tasks:
#    - name: Update APT package cache
#      apt:
#        update_cache: true
#      changed_when: false
#      retries: 5
#      delay: 10
#      register: result
#      until: result is success
#    - name: Creates temp directory ansible
#      file:
#        path: /var/www/.ansible/tmp
#        state: directory
#        owner: www-data
#        group: www-data
#        mode: 0777
#        recurse: yes
